/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attendees/check-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Check in an attendee */
        patch: operations["AttendeeController_checkIn"];
        trace?: never;
    };
    "/api/v1/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login as an admin */
        post: operations["AdminController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh JWT tokens using a valid refresh token */
        post: operations["AdminController_refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a password reset email */
        post: operations["AdminController_forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset admin password */
        post: operations["AdminController_resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated admin profile */
        get: operations["AdminController_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update authenticated admin profile */
        patch: operations["AdminController_updateProfile"];
        trace?: never;
    };
    "/api/v1/admin/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change password for the authenticated admin */
        patch: operations["AdminController_changePassword"];
        trace?: never;
    };
    "/api/v1/admin/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invite another admin (Super Admin only) */
        post: operations["AdminController_inviteAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/deactivate/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Deactivate an admin account (Super Admin only) */
        patch: operations["AdminController_deactivateAdmin"];
        trace?: never;
    };
    "/api/v1/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all admins */
        get: operations["AdminController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List roles */
        get: operations["RolesController_list"];
        put?: never;
        /** Create a role */
        post: operations["RolesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List permissions */
        get: operations["RolesController_listPermssions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a role */
        patch: operations["RolesController_update"];
        trace?: never;
    };
    "/api/v1/roles/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Deactivate a role */
        patch: operations["RolesController_deactivate"];
        trace?: never;
    };
    "/api/v1/roles/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a role by ID */
        get: operations["RolesController_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/initialize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Initialize payment */
        post: operations["PaymentsController_initiatePayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify payment */
        post: operations["PaymentsController_verifyPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PaymentsController_handleWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all payments */
        get: operations["PaymentsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get payment by ID */
        get: operations["PaymentsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tickets */
        get: operations["TicketsController_findAll"];
        put?: never;
        /** Create a ticket */
        post: operations["TicketsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{ticketId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a ticket by ID */
        get: operations["TicketsController_findOneById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a ticket */
        patch: operations["TicketsController_update"];
        trace?: never;
    };
    "/api/v1/tickets/onsale": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tickets currently on sale */
        get: operations["TicketsController_findOnSale"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a ticket by slug */
        get: operations["TicketsController_findBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download a ticket PDF */
        get: operations["TicketsController_download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List orders
         * @description Cursor-paginated list of orders. By default returns earlier-dated orders first.
         */
        get: operations["OrdersController_findAll"];
        put?: never;
        /** Create a ticket order */
        post: operations["OrdersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/reference/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get order by payment reference */
        get: operations["OrdersController_findByReference"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/monnify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive Monnify webhook events */
        post: operations["WebhookController_handleMonnifyWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CheckInOrderDto: {
            /**
             * @description ID of the order being checked in
             * @example 0191a2b3-...
             */
            orderId: string;
        };
        CheckInResponseDto: {
            orderId: string;
            /** @description Ticket code */
            code: string;
            checkIns: string[];
        };
        LoginAdminDto: {
            /**
             * @description Email address
             * @example admin@gdg.com
             */
            email: string;
            /**
             * @description User password
             * @example StrongPassword123!
             */
            password: string;
        };
        Admin: {
            readonly id: string;
            readonly fullName: string;
            readonly role: string;
            readonly email: string;
        };
        LoginResponseDto: {
            readonly admin: components["schemas"]["Admin"];
            readonly accessToken: string;
            readonly refreshToken: string;
        };
        RefreshTokenDto: {
            /**
             * @description Refresh token
             * @example evAdBCX.........
             */
            refreshToken: string;
        };
        ForgotPasswordDto: {
            /**
             * @description Registered email address of the admin
             * @example admin@gdgibadan.com
             */
            email: string;
        };
        ResetPasswordDto: {
            /**
             * @description The password reset token received in the email
             * @example a3f2c1e4d5b6...
             */
            token: string;
            /**
             * @description The new password to set
             * @example NewSecurePass123!
             */
            newPassword: string;
        };
        AdminRoleDto: {
            /**
             * @description Human-readable role name
             * @example VOLUNTEER
             */
            name: string;
            /**
             * @description List of permission IDs granted to this role. These permissions control which actions the admin is authorised to perform.
             * @example [
             *       "tickets.create",
             *       "attendees.list"
             *     ]
             */
            permissions: ("tickets.create" | "tickets.edit" | "tickets.disable" | "attendees.check_in" | "attendees.list" | "admins.create" | "admins.list" | "admins.invite" | "admins.update" | "admins.profile" | "admins.deactivate" | "roles.create" | "roles.edit" | "roles.assign" | "roles.list" | "roles.deactivate" | "permissions.assign" | "payment_reports.export" | "orders.list")[];
        };
        FindOneAdminResponseDto: {
            id: string;
            fullName: string;
            email: string;
            /** @description Role assigned to this admin, including its permission set. */
            role: components["schemas"]["AdminRoleDto"];
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateProfileDto: {
            /**
             * @description Full name of the admin
             * @example Jane Doe
             */
            fullName?: string;
            /**
             * @description New email address for the admin account
             * @example newemail@gdgibadan.com
             */
            email?: string;
        };
        ChangePasswordDto: {
            /**
             * @description Current password of the user
             * @example CurrentPass123!
             */
            currentPassword: string;
            /**
             * @description New password to set
             * @example NewPass123!
             */
            newPassword: string;
        };
        InviteAdminDto: {
            /**
             * @description Full name of the admin
             * @example John Doe
             */
            fullName: string;
            /**
             * @description Email address of the admin
             * @example admin@gdg.com
             */
            email: string;
            /** @description ID of the role to assign to the admin */
            roleId: string;
        };
        AdminActionResponseDto: {
            /**
             * @description Response message
             * @example Operation successful
             */
            message: string;
        };
        FindAllAdminsItemDto: {
            /** @description Admin unique identifier */
            id: string;
            /** @description Admin full name */
            fullName: string;
            /** @description Admin email address */
            email: string;
            /** @description Role assigned to this admin, including its permission set. */
            role: components["schemas"]["AdminRoleDto"];
            /** @description Whether the admin account is active */
            isActive: boolean;
            /** @description ID of the admin who invited this user */
            invitedById: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        FindAllAdminsMetaDto: {
            /** @description Total number of matching admins */
            total: number;
            /** @description Current page number */
            page: number;
            /** @description Number of records per page */
            limit: number;
            /** @description Total number of pages */
            totalPages: number;
        };
        FindAllAdminsResponseDto: {
            data: components["schemas"]["FindAllAdminsItemDto"][];
            meta: components["schemas"]["FindAllAdminsMetaDto"];
        };
        CreateRoleDto: {
            /**
             * @description Name of the role
             * @example VOLUNTEER
             */
            name: string;
            /** @description Description of the role */
            description: string;
            /** @description Permissions for this role */
            permissions: ("tickets.create" | "tickets.edit" | "tickets.disable" | "attendees.check_in" | "attendees.list" | "admins.create" | "admins.list" | "admins.invite" | "admins.update" | "admins.profile" | "admins.deactivate" | "roles.create" | "roles.edit" | "roles.assign" | "roles.list" | "roles.deactivate" | "permissions.assign" | "payment_reports.export" | "orders.list")[];
            isActive: boolean;
        };
        PermissionDto: {
            /** @enum {string} */
            readonly id: "tickets.create" | "tickets.edit" | "tickets.disable" | "attendees.check_in" | "attendees.list" | "admins.create" | "admins.list" | "admins.invite" | "admins.update" | "admins.profile" | "admins.deactivate" | "roles.create" | "roles.edit" | "roles.assign" | "roles.list" | "roles.deactivate" | "permissions.assign" | "payment_reports.export" | "orders.list";
            /** @enum {string} */
            readonly label: "Create tickets" | "Edit tickets" | "Disable tickets" | "Check-in attendees" | "View attendee list" | "Create admin" | "View admin list" | "Invite admin" | "Update admin" | "View admin profile" | "Deactivate admin" | "Create role" | "Edit role" | "Assign role" | "View roles list" | "Deactivate role" | "Assign permissions" | "Export payment report" | "View orders list";
        };
        CreateRoleResponseDto: {
            readonly id: string;
            readonly name: string;
            readonly description: string;
            readonly isActive: boolean;
            readonly permissions: components["schemas"]["PermissionDto"][];
            /** Format: date-time */
            readonly createdAt: string;
        };
        ListRolesItemResponseDto: {
            readonly id: string;
            readonly name: string;
            readonly permissions: components["schemas"]["PermissionDto"][];
            readonly isActive: boolean;
            /** Format: date-time */
            readonly createdAt: string;
        };
        ListRolesResponseDto: {
            readonly roles: components["schemas"]["ListRolesItemResponseDto"][];
        };
        ListPermissionsResponse: {
            permissions: components["schemas"]["PermissionDto"][];
        };
        UpdateRoleDto: {
            /**
             * @description Name of the role
             * @example VOLUNTEER
             */
            name?: string;
            /** @description Description of the role */
            description?: string;
            /** @description Permissions for this role */
            permissions?: ("tickets.create" | "tickets.edit" | "tickets.disable" | "attendees.check_in" | "attendees.list" | "admins.create" | "admins.list" | "admins.invite" | "admins.update" | "admins.profile" | "admins.deactivate" | "roles.create" | "roles.edit" | "roles.assign" | "roles.list" | "roles.deactivate" | "permissions.assign" | "payment_reports.export" | "orders.list")[];
            isActive?: boolean;
        };
        RoleResponseDto: {
            /** @description Unique identifier of the role */
            id: string;
            /**
             * @description Name of the role
             * @example ADMIN
             */
            name: string;
            /**
             * @description Description of the role
             * @example Administrator with access to manage admins and tickets
             */
            description: string;
            /**
             * @description Permissions assigned to the role
             * @example [
             *       "Create tickets",
             *       "Edit tickets",
             *       "Invite admin"
             *     ]
             */
            permissions: unknown[][];
            /**
             * @description Whether the role is currently active
             * @example true
             */
            isActive: boolean;
            /**
             * Format: date-time
             * @description Date the role was created
             * @example 2026-08-20T10:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Date the role was last updated
             * @example 2026-08-20T14:20:00.000Z
             */
            updatedAt: string;
        };
        GetRoleResponseDto: {
            readonly id: string;
            readonly name: string;
            readonly description: string;
            readonly isActive: boolean;
            readonly permissions: components["schemas"]["PermissionDto"][];
            readonly activeAdminCount: number;
            /** Format: date-time */
            readonly createdAt: string;
        };
        InitiatePaymentDto: {
            /**
             * @description Unique identifier of the attendee making the payment
             * @example att_1234567890abcdef
             */
            attendeeId: string;
            /**
             * @description Email address of the attendee making the payment
             * @example john.doe@example.com
             */
            email: string;
            /**
             * @description Amount to be paid in the smallest currency unit (e.g., Naira kobo)
             * @example 5000
             */
            amount: number;
        };
        VerifyPaymentDto: {
            /**
             * @description Unique payment reference generated by the payment gateway to identify the transaction
             * @example pay_1234567890abcdef
             */
            reference: string;
        };
        CreateTicketDto: {
            name: string;
            description: string;
            /**
             * @description Event dates in YYYY-MM-DD format
             * @example [
             *       "2026-08-17",
             *       "2026-08-18"
             *     ]
             */
            eventDates: string[];
            /** @description Price of ticket in Naira */
            price: number;
            /**
             * @description Ticket discount in Naira
             * @default 0
             */
            discount: number;
            /**
             * @description Validity dates in YYYY-MM-DD format. Each date must be present in `eventDates`
             * @example [
             *       "2026-08-17",
             *       "2026-08-18"
             *     ]
             */
            validityDates: string[];
            /** @description Maximum units of this ticket available for sale */
            capacity: number;
            /**
             * Format: date-time
             * @description Sales will start at the beginning of this day
             */
            saleStartsAt: string;
            /**
             * Format: date-time
             * @description Sales will end at the end of this day
             */
            saleEndsAt: string;
        };
        CreateTicketResponseDto: {
            id: string;
            name: string;
            description: string;
            slug: string;
            eventDates: string[];
            /**
             * @description Price in Naira (formatted to 2 decimal places)
             * @example 10000.00
             */
            price: string;
            /**
             * @description Discount in Naira (formatted to 2 decimal places)
             * @example 500.00
             */
            discount: string;
            validityDates: string[];
            capacity: number;
            /** Format: date-time */
            saleStartsAt: string;
            /** Format: date-time */
            saleEndsAt: string;
            /** Format: date-time */
            createdAt: string;
        };
        TicketListItemDto: {
            id: string;
            name: string;
            eventDates: string[];
            /**
             * @description Price in Naira (formatted to 2 decimal places)
             * @example 10000.00
             */
            price: string;
            /**
             * @description Discount in Naira (formatted to 2 decimal places)
             * @example 500.00
             */
            discount: string;
            /** Format: date-time */
            saleStartsAt: string;
            /** Format: date-time */
            saleEndsAt: string;
            capacity: number;
            slug: string;
        };
        TicketPaginationMetaDto: {
            /** @description Cursor to fetch the next page */
            nextCursor: string | null;
            /** @description Cursor to fetch the previous page */
            prevCursor: string | null;
            /** @description Number of results per page */
            limit: number;
            /** @description Whether more items exist in the forward direction */
            hasMore: boolean;
        };
        TicketListResponseDto: {
            data: components["schemas"]["TicketListItemDto"][];
            meta: components["schemas"]["TicketPaginationMetaDto"];
        };
        OnSaleTicketItemDto: {
            name: string;
            description: string;
            slug: string;
            validityDates: string[];
            eventDates: string[];
            /**
             * @description Price in Naira (formatted to 2 decimal places)
             * @example 10000.00
             */
            price: string;
            /**
             * @description Discount in Naira (formatted to 2 decimal places)
             * @example 500.00
             */
            discount: string;
        };
        OnSaleTicketResponseDto: {
            data: components["schemas"]["OnSaleTicketItemDto"][];
        };
        GetTicketBySlugResponseDto: {
            name: string;
            description: string;
            /**
             * @description Price in Naira (formatted to 2 decimal places)
             * @example 10000.00
             */
            price: string;
            /**
             * @description Discount in Naira (formatted to 2 decimal places)
             * @example 500.00
             */
            discount: string;
            eventDates: string[];
            validityDates: string[];
            slug: string;
        };
        TicketCreatorDto: {
            name: string;
            role: string;
        };
        GetTicketResponseDto: {
            id: string;
            name: string;
            slug: string;
            description: string;
            eventDates: string[];
            /**
             * @description Price in Naira (formatted to 2 decimal places)
             * @example 10000.00
             */
            price: string;
            /**
             * @description Discount in Naira (formatted to 2 decimal places)
             * @example 500.00
             */
            discount: string;
            validityDates: string[];
            capacity: number;
            /** Format: date-time */
            saleStartsAt: string;
            /** Format: date-time */
            saleEndsAt: string;
            /** Format: date-time */
            createdAt: string;
            creator: components["schemas"]["TicketCreatorDto"];
        };
        OrderAttendeeDto: {
            /** @example Ada Obi */
            fullName: string;
            /** @example ada@example.com */
            email: string;
            /** @example 08012345678 */
            phoneNumber?: string;
        };
        OrderGifterDto: {
            /** @example Tunde Bello */
            fullName: string;
            /**
             * @description Used as the payment customer email on the payment gateway
             * @example tunde@example.com
             */
            email: string;
        };
        CreateOrderDto: {
            /**
             * @description Slug of the ticket to purchase
             * @example early-bird-2026-08-17
             */
            slug: string;
            attendee: components["schemas"]["OrderAttendeeDto"];
            /** @description Presence indicates the ticket is a gift */
            gifter?: components["schemas"]["OrderGifterDto"];
        };
        OrderedTicketDto: {
            name: string;
            slug: string;
        };
        CreateOrderResponseDto: {
            id: string;
            reference: string;
            /** @enum {string} */
            status: "AWAITING_PAYMENT";
            /**
             * @description Total amount payable in Naira (2 decimal places)
             * @example 9500.00
             */
            amount: string;
            /**
             * @description Discount applied in Naira (2 decimal places)
             * @example 500.00
             */
            discount: string;
            /**
             * @description 7.5% VAT plus payment gateway service charge
             * @example 500.00
             */
            vatAndCharges: string;
            currency: string;
            /** @description Payment checkout URL to redirect the payer to */
            checkoutUrl: string | null;
            /** Format: date-time */
            expiresAt: string;
            ticket: components["schemas"]["OrderedTicketDto"];
        };
        OrderListItemDto: {
            id: string;
            /** Format: date-time */
            paidAt: string | null;
            /**
             * @description Amount paid in Naira (2 decimal places)
             * @example 9500.00
             */
            amount: string;
            /** @enum {string} */
            status: "AWAITING_PAYMENT" | "PAID" | "CANCELLED" | "AWAITING_REFUND" | "REFUNDED";
            attendeeFullName: string;
            attendeeEmail: string;
            checkIns: string[];
            ticket: {
                id?: string;
                /** @example Early Bird */
                name?: string;
                /** @example ABC123 */
                code?: string;
                /** @example Fri + Sat */
                validity?: string;
            };
        };
        OrdersPaginationMetaDto: {
            /** @description Cursor to fetch the next page */
            nextCursor: string | null;
            /** @description Cursor to fetch the previous page */
            prevCursor: string | null;
            /** @description Number of results per page */
            limit: number;
            /** @description Whether more items exist in the direction of travel */
            hasMore: boolean;
        };
        OrderListResponseDto: {
            data: components["schemas"]["OrderListItemDto"][];
            meta: components["schemas"]["OrdersPaginationMetaDto"];
        };
        GetOrderReferenceResponseDto: {
            ticket: {
                /** @example Early Bird */
                name?: string;
                /** @example https://example.com/download/ticket.pdf */
                url?: string;
                /**
                 * @example [
                 *       "2026-09-20T00:00:00.000Z",
                 *       "2026-09-21T00:00:00.000Z"
                 *     ]
                 */
                validityDates?: string[];
            };
            /**
             * @description Amount paid in Naira (2 decimal places)
             * @example 9500.00
             */
            amount: string;
            /** @enum {string} */
            status: "AWAITING_PAYMENT" | "PAID" | "CANCELLED" | "AWAITING_REFUND" | "REFUNDED";
            /**
             * @description Ticket code
             * @example ABC123
             */
            code: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AttendeeController_checkIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckInOrderDto"];
            };
        };
        responses: {
            /** @description Attendee checked in successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckInResponseDto"];
                };
            };
            /** @description Ticket not valid for today */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing attendees.check_in permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ticket not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginAdminDto"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
            /** @description Invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            /** @description Tokens refreshed successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or expired refresh token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordDto"];
            };
        };
        responses: {
            /** @description Password reset link has been sent to the provided email address. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForgotPasswordDto"];
                };
            };
            /** @description Invalid credentials. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordDto"];
            };
        };
        responses: {
            /** @description Password reset successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetPasswordDto"];
                };
            };
            /** @description Invalid token. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile retrieved successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindOneAdminResponseDto"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            /** @description Profile updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateProfileDto"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            /** @description Password changed successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePasswordDto"];
                };
            };
            /** @description New password must differ from the current one. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Current password is incorrect. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_inviteAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteAdminDto"];
            };
        };
        responses: {
            /** @description Admin invited successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteAdminDto"];
                };
            };
            /** @description Only SUPER_ADMIN can invite other admins. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_deactivateAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Admin deactivated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminActionResponseDto"];
                };
            };
            /** @description Only SUPER_ADMIN can deactivate other admins. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_findAll: {
        parameters: {
            query?: {
                /** @description Search term to filter admins by name or email */
                search?: string;
                /** @description Filter admins by role name */
                role?: string;
                /** @description Filter admins by active status */
                isActive?: boolean;
                /** @description Page number for pagination */
                page?: number;
                /** @description Number of records per page */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Admins retrieved successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindAllAdminsResponseDto"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRolesResponseDto"];
                };
            };
        };
    };
    RolesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRoleResponseDto"];
                };
            };
        };
    };
    RolesController_listPermssions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPermissionsResponse"];
                };
            };
        };
    };
    RolesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleResponseDto"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleResponseDto"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRoleResponseDto"];
                };
            };
        };
    };
    PaymentsController_initiatePayment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitiatePaymentDto"];
            };
        };
        responses: {
            /** @description Payment initialized successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentsController_verifyPayment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyPaymentDto"];
            };
        };
        responses: {
            /** @description Payment verified successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentsController_handleWebhook: {
        parameters: {
            query?: never;
            header: {
                "x-paystack-signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentsController_findAll: {
        parameters: {
            query: {
                page: number;
                limit: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payments retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payment retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TicketsController_findAll: {
        parameters: {
            query?: {
                /** @description Cursor for pagination. Pass the ID of the last item from the previous page. */
                cursor?: string;
                /** @description Pagination direction */
                direction?: "next" | "previous";
                /** @description Number of results to return per page */
                limit?: number;
                /** @description Ticket name (case-insensitive) */
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tickets retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketListResponseDto"];
                };
            };
        };
    };
    TicketsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTicketDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTicketResponseDto"];
                };
            };
        };
    };
    TicketsController_findOneById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ticket retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetTicketResponseDto"];
                };
            };
        };
    };
    TicketsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTicketDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTicketResponseDto"];
                };
            };
        };
    };
    TicketsController_findOnSale: {
        parameters: {
            query?: {
                /** @description Filter tickets by name (case-insensitive) */
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tickets retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnSaleTicketResponseDto"];
                };
            };
        };
    };
    TicketsController_findBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ticket retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetTicketBySlugResponseDto"];
                };
            };
            /** @description Ticket not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TicketsController_download: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to ticket PDF */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid token or ticket not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersController_findAll: {
        parameters: {
            query?: {
                /** @description Search orders by attendee email, attendee full name, or reference (case-insensitive) */
                search?: string;
                /** @description Filter by order status. When omitted, orders of all statuses are returned. */
                status?: "AWAITING_PAYMENT" | "PAID" | "CANCELLED" | "AWAITING_REFUND" | "REFUNDED";
                /** @description Pagination direction. `next` returns earlier-dated orders, `previous` returns more recent orders. */
                direction?: "next" | "previous";
                /** @description Cursor for pagination. Pass the ID of the last item from the previous page. */
                cursor?: string;
                /** @description Number of results per page (default 20, max 50) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Orders retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderListResponseDto"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requires permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderDto"];
            };
        };
        responses: {
            /** @description Order created and payment initialized */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateOrderResponseDto"];
                };
            };
            /** @description Ticket not on sale or invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ticket not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ticket sold out, all remaining units reserved, or duplicate order for attendee */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Payment initialization failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersController_findByReference: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetOrderReferenceResponseDto"];
                };
            };
            /** @description Order not found for reference */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WebhookController_handleMonnifyWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
