import type { AttendeeRecord } from '../_types/attendee.types';

const MOCK_ATTENDEES: AttendeeRecord[] = [
  {
    id: '1',
    ticketId: 'TKT-001',
    date: '12th Aug, 2025',
    fullName: 'Adesola Okonkwo',
    email: 'adesola@example.com',
    code: 'DEV-A1B2',
    eventDays: 'Friday & Saturday',
    amount: '₦8,000',
    status: 'Successful',
  },
  {
    id: '2',
    ticketId: 'TKT-002',
    date: '12th Aug, 2025',
    fullName: 'Chukwuemeka Nwosu',
    email: 'emeka@example.com',
    code: 'DEV-C3D4',
    eventDays: 'Saturday',
    amount: '₦8,000',
    status: 'Pending',
  },
  {
    id: '3',
    ticketId: 'TKT-003',
    date: '13th Aug, 2025',
    fullName: 'Fatima Bello',
    email: 'fatima@example.com',
    code: 'DEV-E5F6',
    eventDays: 'Friday',
    amount: '₦4,000',
    status: 'Successful',
  },
  {
    id: '4',
    ticketId: 'TKT-004',
    date: '13th Aug, 2025',
    fullName: 'Olumide Adeyemi',
    email: 'olumide@example.com',
    code: 'DEV-G7H8',
    eventDays: 'Friday & Saturday',
    amount: '₦8,000',
    status: 'Failed',
  },
  {
    id: '5',
    ticketId: 'TKT-005',
    date: '14th Aug, 2025',
    fullName: 'Ngozi Eze',
    email: 'ngozi@example.com',
    code: 'DEV-I9J0',
    eventDays: 'Saturday',
    amount: '₦8,000',
    status: 'Successful',
  },
  {
    id: '6',
    ticketId: 'TKT-006',
    date: '14th Aug, 2025',
    fullName: 'Seun Abiodun',
    email: 'seun@example.com',
    code: 'DEV-K1L2',
    eventDays: 'Friday & Saturday',
    amount: '₦8,000',
    status: 'Pending',
  },
];

export default MOCK_ATTENDEES;